Github Action: build PPA in repo

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -31,6 +31,7 @@ jobs:
     - name: Install
       run: ./tests/test_kernel_install.sh
       shell: bash
+
   run-kernel-module-test:
     runs-on: ubuntu-latest
     steps:
@@ -48,6 +49,7 @@ jobs:
     - name: Test Reload Second
       run: ./tests/test_kernel_reload.sh
       shell: bash
+
   run-kernel-dkms-install-test:
     runs-on: ubuntu-latest
     steps:
@@ -59,6 +61,7 @@ jobs:
     - name: Build
       run: ./tests/test_kenel_dkms_install.sh || true
       shell: bash
+
   run-tests:
     name: Run Tests
     runs-on: ubuntu-latest
@@ -88,23 +91,7 @@ jobs:
         if: always()
         run: ./deploy/python_install_pip_pkg.sh
         shell: bash
-  test-in-docker-container:
-    runs-on: ubuntu-latest
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v3
-    - name: Build containers and run tests inside them
-      run: ./deploy/build_containers.sh
-      shell: bash
-  test-packages:
-    runs-on: ubuntu-latest
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v3
-    - name: Build containers and run tests inside them
-      run: |
-        ./deploy/package_testing/build_containers.sh
-      shell: bash
+
   release-kernel-patch:
     needs: [build, run-kernel-module-test, run-kernel-dkms-install-test, run-tests]
     runs-on: ubuntu-latest
@@ -164,3 +151,176 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         release_id: ${{ steps.create_release.outputs.id }}
+
+  test-in-docker-container:
+    needs: [build, run-tests]
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+    - name: Build containers and run tests inside them
+      run: ./deploy/build_containers.sh
+      shell: bash
+
+  build-test-commit-debs:
+    needs: [test-in-docker-container]
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+
+## ADD IF NOT FAIL
+#    - name: Check if tagged
+#      id: check_if_tagged
+#      run: |
+#        otag=$(git tag --points-at HEAD)
+#        echo "Tag is ${otag}"
+#        if [ -z "$otag" ]
+#        then
+#          hastag=0
+#        else
+#          hastag=1
+#        fi
+#        echo "hastag=$hastag" >> $GITHUB_OUTPUT
+
+    - name: Update submodules
+      run: |
+        git submodule update --init
+        git pull --recurse-submodules
+        git submodule update --remote --recursive
+      shell: bash
+
+    - name: Install Dependencies
+      run: ./deploy/dependencies/install_dependencies_ubuntu.sh
+      shell: bash
+
+    - name: Build deb darkdetect
+      run: ./deploy/build_packages/build_deb_darkdetect.sh
+      shell: bash
+
+    - name: Build pkgs LenovoLegionLinux
+      run: |
+        ./deploy/build_packages/build_deb_LLL.sh
+      shell: bash
+
+    - name: Import GPG key
+      uses: crazy-max/ghaction-import-gpg@v5
+      with:
+        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
+
+    - name: Copy and Generate files - Ubuntu
+      run: |
+        cd package_repo/ubuntu
+        gpg --armor --export "${{ secrets.GPG_ID }}" > ./KEY.gpg
+        dpkg-scanpackages --multiversion . > Packages
+        gzip -k -f Packages
+        apt-ftparchive release . > Release
+        gpg --default-key "${{ secrets.GPG_ID }}" -abs -o - Release > Release.gpg
+        gpg --default-key "${{ secrets.GPG_ID }}" --clearsign -o - Release > InRelease
+        echo "deb [signed-by=/usr/share/keyrings/lll-ppa.gpg] https://mrduartept.github.io/LLL-pkg-repo/ubuntu ./" > lll-ppa.list
+      shell: bash
+
+    - name: Commit changes
+      #if: steps.check_if_tagged.outputs.hastag == 1
+      run: |
+        git fetch
+        git add -A
+        git config user.name github-actions
+        git config user.email github-actions@github.com
+        git commit -m "Add new debs"
+        git pull --rebase
+        git push
+      shell: bash
+
+
+  build-test-commit-rpms:
+    needs: [test-in-docker-container]
+    runs-on: ubuntu-latest
+    container:
+      image: fedora:38
+    steps:
+    - name: Install Dependencies in Container
+      run: |
+        sudo dnf install -y git kernel-headers kernel-devel dmidecode lm_sensors PyQt5 python3-yaml python3-pip python3-argcomplete polkit rpmdevtools rpmlint rpm rpm-sign
+        sudo dnf install -y dkms openssl mokutil
+      shell: bash
+
+    - name: Clone repo and submodules
+      uses: actions/checkout@v3
+
+## ADD IF NOT FAIL
+#    - name: Check if tagged
+#      id: check_if_tagged
+#      run: |
+#        otag=$(git tag --points-at HEAD)
+#        echo "Tag is ${otag}"
+#        if [ -z "$otag" ]
+#        then
+#          hastag=0
+#        else
+#          hastag=1
+#        fi
+#        echo "hastag=$hastag" >> $GITHUB_OUTPUT
+
+    - name: Update submodules
+      run: |
+        git submodule update --init
+        git pull --recurse-submodules
+        git submodule update --remote --recursive
+      shell: bash
+
+    - name: Build rpm darkdetect
+      run: |
+        cd LLL-pkg-repo
+        ./deploy/build_packages/build_rpm_darkdetect.sh
+      shell: bash
+
+    - name: Build rpm LenovoLegionLinux
+      run: |
+        cd LLL-pkg-repo
+        ./deploy/build_packages/build_rpm_LLL.sh
+      shell: bash
+
+    - name: Import GPG key
+      uses: crazy-max/ghaction-import-gpg@v5
+      with:
+        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
+
+    - name: Copy and Generate files - Fedora
+      run: |
+        cd package_repo/fedora
+        gpg --armor --export "${{ secrets.GPG_ID }}" > ./pgp-key.public
+        sudo rpm --import pgp-key.public
+        echo "%_signature gpg
+        %_gpg_name Package Manager" > ~/.rpmmacros
+        rpm --addsign ./packages/*.rpm
+        cd packages
+        rm repodata/* || true
+        createrepo_c .
+        gpg --batch --detach-sign --armor repodata/repomd.xml
+
+      shell: bash
+
+    - name: Commit changes
+      #if: steps.check_if_tagged.outputs.hastag == 1
+      run: |
+        cd LLL-pkg-repo
+        git fetch
+        git add -A
+        git config user.name github-actions
+        git config user.email github-actions@github.com
+        git commit -m "Add new rpms"
+        git pull --rebase
+        git push
+      shell: bash
+
+  test-packages:
+    needs: [build-test-commit-debs, uild-test-commit-rpms]
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+    - name: Build containers and run tests inside them
+      run: |
+        ./deploy/package_testing/build_containers.sh
+      shell: bash
